[package]
name = "dyno"
version = "0.1.0"
edition = "2024"
description = "Tree-structured robot kinematics and dynamics with fixed-size joint-space calculation types"
license = "MIT"

[features]
default = []
core-bench = ["dep:criterion"]
pinocchio-bench = ["dep:cc", "dep:criterion", "dep:pkg-config"]

[dependencies]
criterion = { version = "0.7.0", optional = true }
nalgebra = "0.34.1"
urdf-rs = "0.9.0"

[dev-dependencies]
approx = "0.5.1"

[build-dependencies]
cc = { version = "1.2.49", optional = true }
pkg-config = { version = "0.3.32", optional = true }

[[bench]]
name = "pinocchio"
harness = false
required-features = ["pinocchio-bench"]

[[bench]]
name = "core"
harness = false
required-features = ["core-bench"]

[profile.release]
codegen-units = 1
lto = "fat"
